// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: profile.proto

package profileGRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileClient interface {
	Add(ctx context.Context, in *ProfileWithoutIdSystemField, opts ...grpc.CallOption) (*ProfileId, error)
	Edit(ctx context.Context, in *ProfileWithoutSystemField, opts ...grpc.CallOption) (*EmptyResponse, error)
	Delete(ctx context.Context, in *ProfileId, opts ...grpc.CallOption) (*EmptyResponse, error)
	Item(ctx context.Context, in *ProfileId, opts ...grpc.CallOption) (*ProfileWithoutPassword, error)
	List(ctx context.Context, in *ProfilePaginator, opts ...grpc.CallOption) (*ProfileList, error)
	EditWithoutPassword(ctx context.Context, in *ProfileWithoutIdSystemFieldPassword, opts ...grpc.CallOption) (*EmptyResponse, error)
	ChangePassword(ctx context.Context, in *ProfilePassword, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetByEmailOrPhone(ctx context.Context, in *ProfileEmailPhonePassword, opts ...grpc.CallOption) (*ProfileWithoutPassword, error)
}

type profileClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileClient(cc grpc.ClientConnInterface) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) Add(ctx context.Context, in *ProfileWithoutIdSystemField, opts ...grpc.CallOption) (*ProfileId, error) {
	out := new(ProfileId)
	err := c.cc.Invoke(ctx, "/profile.Profile/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Edit(ctx context.Context, in *ProfileWithoutSystemField, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/profile.Profile/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Delete(ctx context.Context, in *ProfileId, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/profile.Profile/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Item(ctx context.Context, in *ProfileId, opts ...grpc.CallOption) (*ProfileWithoutPassword, error) {
	out := new(ProfileWithoutPassword)
	err := c.cc.Invoke(ctx, "/profile.Profile/Item", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) List(ctx context.Context, in *ProfilePaginator, opts ...grpc.CallOption) (*ProfileList, error) {
	out := new(ProfileList)
	err := c.cc.Invoke(ctx, "/profile.Profile/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) EditWithoutPassword(ctx context.Context, in *ProfileWithoutIdSystemFieldPassword, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/profile.Profile/EditWithoutPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) ChangePassword(ctx context.Context, in *ProfilePassword, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/profile.Profile/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetByEmailOrPhone(ctx context.Context, in *ProfileEmailPhonePassword, opts ...grpc.CallOption) (*ProfileWithoutPassword, error) {
	out := new(ProfileWithoutPassword)
	err := c.cc.Invoke(ctx, "/profile.Profile/GetByEmailOrPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
// All implementations must embed UnimplementedProfileServer
// for forward compatibility
type ProfileServer interface {
	Add(context.Context, *ProfileWithoutIdSystemField) (*ProfileId, error)
	Edit(context.Context, *ProfileWithoutSystemField) (*EmptyResponse, error)
	Delete(context.Context, *ProfileId) (*EmptyResponse, error)
	Item(context.Context, *ProfileId) (*ProfileWithoutPassword, error)
	List(context.Context, *ProfilePaginator) (*ProfileList, error)
	EditWithoutPassword(context.Context, *ProfileWithoutIdSystemFieldPassword) (*EmptyResponse, error)
	ChangePassword(context.Context, *ProfilePassword) (*EmptyResponse, error)
	GetByEmailOrPhone(context.Context, *ProfileEmailPhonePassword) (*ProfileWithoutPassword, error)
	mustEmbedUnimplementedProfileServer()
}

// UnimplementedProfileServer must be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (UnimplementedProfileServer) Add(context.Context, *ProfileWithoutIdSystemField) (*ProfileId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedProfileServer) Edit(context.Context, *ProfileWithoutSystemField) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedProfileServer) Delete(context.Context, *ProfileId) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProfileServer) Item(context.Context, *ProfileId) (*ProfileWithoutPassword, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Item not implemented")
}
func (UnimplementedProfileServer) List(context.Context, *ProfilePaginator) (*ProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProfileServer) EditWithoutPassword(context.Context, *ProfileWithoutIdSystemFieldPassword) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditWithoutPassword not implemented")
}
func (UnimplementedProfileServer) ChangePassword(context.Context, *ProfilePassword) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedProfileServer) GetByEmailOrPhone(context.Context, *ProfileEmailPhonePassword) (*ProfileWithoutPassword, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByEmailOrPhone not implemented")
}
func (UnimplementedProfileServer) mustEmbedUnimplementedProfileServer() {}

// UnsafeProfileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServer will
// result in compilation errors.
type UnsafeProfileServer interface {
	mustEmbedUnimplementedProfileServer()
}

func RegisterProfileServer(s grpc.ServiceRegistrar, srv ProfileServer) {
	s.RegisterService(&Profile_ServiceDesc, srv)
}

func _Profile_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileWithoutIdSystemField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Add(ctx, req.(*ProfileWithoutIdSystemField))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileWithoutSystemField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Edit(ctx, req.(*ProfileWithoutSystemField))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Delete(ctx, req.(*ProfileId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Item_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Item(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/Item",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Item(ctx, req.(*ProfileId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfilePaginator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).List(ctx, req.(*ProfilePaginator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_EditWithoutPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileWithoutIdSystemFieldPassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).EditWithoutPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/EditWithoutPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).EditWithoutPassword(ctx, req.(*ProfileWithoutIdSystemFieldPassword))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfilePassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).ChangePassword(ctx, req.(*ProfilePassword))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetByEmailOrPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileEmailPhonePassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetByEmailOrPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/GetByEmailOrPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetByEmailOrPhone(ctx, req.(*ProfileEmailPhonePassword))
	}
	return interceptor(ctx, in, info, handler)
}

// Profile_ServiceDesc is the grpc.ServiceDesc for Profile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Profile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Profile_Add_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _Profile_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Profile_Delete_Handler,
		},
		{
			MethodName: "Item",
			Handler:    _Profile_Item_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Profile_List_Handler,
		},
		{
			MethodName: "EditWithoutPassword",
			Handler:    _Profile_EditWithoutPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Profile_ChangePassword_Handler,
		},
		{
			MethodName: "GetByEmailOrPhone",
			Handler:    _Profile_GetByEmailOrPhone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
